### PR TITLE
Implement OpenQASM compiler

### PR DESCRIPTION
**Pull request by czhao39**

### CODE REVIEW

**Comment by amccaskey** [comment]
@czhao39 This all looks really good. But I do have a few things I'd like addressed before accepting this: 

1. Is the use of isnan() correct in your Listener? It seems to me this will only check Nan and Inf. I'd prefer using something like 
```cpp
auto is_double = [](const std::string& s) -> bool
	{
	    try {
		std::stod(s);
	    } catch(std::exception& e) {
		return false;
	    }
	    return true;
	};
```

2. Strings coming in will have '__qpu__ f(...)' in them. We need to remove that string and grab the parameter variable names and add them to the Function. See lines 95-114 of QuilCompiler. Actually, it may be best to update the Grammar to have these function signatures.

3. We need to set this up to take a string that has multiple Kernels that may reference each other.

**Comment by czhao39** [comment]
I've fixed the issues. Let me know if you have any other suggestions!

**Comment by amccaskey** [comment]
@czhao39 One thing I see - will you please move the Error Listener into an HPP file?

**Comment by amccaskey** [comment]
like the OQASMCompiler.hpp

**Pull request merged**
